/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicaluserinterface;

import javax.swing.JOptionPane;

/**
 *
 * @author Esa
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        bodyPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        calmTitle = new javax.swing.JButton();
        thickTitle = new javax.swing.JButton();
        hotTitle = new javax.swing.JButton();
        cinderTitle = new javax.swing.JButton();
        aboutTitle = new javax.swing.JButton();
        logoutTitle = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        thickPanel = new javax.swing.JPanel();
        hotPanelTitle1 = new javax.swing.JLabel();
        hotPanel = new javax.swing.JPanel();
        hotPanelTitle = new javax.swing.JLabel();
        cinderPanel = new javax.swing.JPanel();
        cinderPanelTitle = new javax.swing.JLabel();
        calmPanel = new javax.swing.JPanel();
        calmPanelTitle = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setTitle("Main Menu");
        setBackground(new java.awt.Color(0, 0, 0));

        bodyPanel.setBackground(new java.awt.Color(0, 0, 0));
        bodyPanel.setForeground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));
        titlePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        titlePanel.setForeground(new java.awt.Color(255, 255, 255));

        calmTitle.setText("calm");
        calmTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calmTitleActionPerformed(evt);
            }
        });

        thickTitle.setText("Thick");
        thickTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thickTitleActionPerformed(evt);
            }
        });

        hotTitle.setText("hot");
        hotTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotTitleActionPerformed(evt);
            }
        });

        cinderTitle.setText("cinder");
        cinderTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinderTitleActionPerformed(evt);
            }
        });

        aboutTitle.setText("about");
        aboutTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutTitleActionPerformed(evt);
            }
        });

        logoutTitle.setText("logout");
        logoutTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calmTitle)
                .addGap(19, 19, 19))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(aboutTitle)
                .addGap(26, 26, 26)
                .addComponent(logoutTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(thickTitle)
                    .addContainerGap(258, Short.MAX_VALUE)))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(hotTitle)
                    .addContainerGap(181, Short.MAX_VALUE)))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                    .addContainerGap(176, Short.MAX_VALUE)
                    .addComponent(cinderTitle)
                    .addGap(98, 98, 98)))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calmTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutTitle)
                    .addComponent(logoutTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(thickTitle)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hotTitle)
                    .addContainerGap(40, Short.MAX_VALUE)))
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(titlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cinderTitle)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        thickPanel.setBackground(new java.awt.Color(0, 0, 0));
        thickPanel.setForeground(new java.awt.Color(255, 255, 255));

        hotPanelTitle1.setBackground(new java.awt.Color(0, 0, 0));
        hotPanelTitle1.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        hotPanelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        hotPanelTitle1.setText("THisnk af");

        javax.swing.GroupLayout thickPanelLayout = new javax.swing.GroupLayout(thickPanel);
        thickPanel.setLayout(thickPanelLayout);
        thickPanelLayout.setHorizontalGroup(
            thickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thickPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(hotPanelTitle1)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        thickPanelLayout.setVerticalGroup(
            thickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thickPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotPanelTitle1)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        mainPanel.add(thickPanel, "card2");

        hotPanel.setBackground(new java.awt.Color(0, 0, 0));
        hotPanel.setForeground(new java.awt.Color(255, 255, 255));

        hotPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        hotPanelTitle.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        hotPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        hotPanelTitle.setText("Hot AF");

        javax.swing.GroupLayout hotPanelLayout = new javax.swing.GroupLayout(hotPanel);
        hotPanel.setLayout(hotPanelLayout);
        hotPanelLayout.setHorizontalGroup(
            hotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(hotPanelTitle)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        hotPanelLayout.setVerticalGroup(
            hotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotPanelTitle)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        mainPanel.add(hotPanel, "card3");

        cinderPanel.setBackground(new java.awt.Color(0, 0, 0));
        cinderPanel.setForeground(new java.awt.Color(255, 255, 255));

        cinderPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        cinderPanelTitle.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        cinderPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        cinderPanelTitle.setText("Cinder");

        javax.swing.GroupLayout cinderPanelLayout = new javax.swing.GroupLayout(cinderPanel);
        cinderPanel.setLayout(cinderPanelLayout);
        cinderPanelLayout.setHorizontalGroup(
            cinderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinderPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(cinderPanelTitle)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        cinderPanelLayout.setVerticalGroup(
            cinderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cinderPanelTitle)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        mainPanel.add(cinderPanel, "card4");

        calmPanel.setBackground(new java.awt.Color(0, 0, 0));
        calmPanel.setForeground(new java.awt.Color(255, 255, 255));

        calmPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        calmPanelTitle.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        calmPanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        calmPanelTitle.setText("Contoh Swing");

        javax.swing.GroupLayout calmPanelLayout = new javax.swing.GroupLayout(calmPanel);
        calmPanel.setLayout(calmPanelLayout);
        calmPanelLayout.setHorizontalGroup(
            calmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calmPanelLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(calmPanelTitle)
                .addGap(69, 69, 69))
        );
        calmPanelLayout.setVerticalGroup(
            calmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calmPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(calmPanelTitle)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        mainPanel.add(calmPanel, "card5");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void thickTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thickTitleActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(thickPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_thickTitleActionPerformed

    private void hotTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotTitleActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(hotPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_hotTitleActionPerformed

    private void cinderTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinderTitleActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(cinderPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_cinderTitleActionPerformed

    private void calmTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calmTitleActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(calmPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_calmTitleActionPerformed

    private void aboutTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutTitleActionPerformed
        // TODO add your handling code here:
        
        About n = new About();
        n.setVisible(true);

    }//GEN-LAST:event_aboutTitleActionPerformed

    private void logoutTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutTitleActionPerformed
        // TODO add your handling code here:
        int dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "yakin kaluar?", null, dialogbtn);

        if (dialogResult == 0) {
            System.exit(0);
        } else {

        }
        
        Login n = new Login();
        n.setVisible(true);
        
    }//GEN-LAST:event_logoutTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutTitle;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel calmPanel;
    private javax.swing.JLabel calmPanelTitle;
    private javax.swing.JButton calmTitle;
    private javax.swing.JPanel cinderPanel;
    private javax.swing.JLabel cinderPanelTitle;
    private javax.swing.JButton cinderTitle;
    private javax.swing.JPanel hotPanel;
    private javax.swing.JLabel hotPanelTitle;
    private javax.swing.JLabel hotPanelTitle1;
    private javax.swing.JButton hotTitle;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JButton logoutTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel thickPanel;
    private javax.swing.JButton thickTitle;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
